version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9001:9001"
    environment:
      #      KAFKA_BROKERCONNECT: "kafka:29092"
      KAFKA_BROKERCONNECT: "localhost:9094"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - zookeeper
      - kafka
  kowl:
    image: quay.io/cloudhut/kowl:master
    restart: "no"
    ports:
      - "38081:8080"
    environment:
      #      KAFKA_BROKERS: "kafka:29092"
      KAFKA_BROKERS: "localhost:29092"
    depends_on:
      - kafdrop