server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: 'localhost:9092'
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  profiles:
    active: dev
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/books?serverTimezone=UTC'
    username: root
    password: change-me
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: false
kafka:
  bootstrap-servers: 'localhost:9092'
  consumergroup: demo
  topic:
    requestreply-topic: requestreply-topic
    request-topic: request-topic
    create-entry-topic: create-entry-topic
    topic-for-demo: topic-for-demo
